const REF = window.JSON_BUILDER_REFERENCE || { buff_refs: [], skill_refs: [], summon_refs: [], state_refs: ["HP", "MP", "FP", "行動値", "速度値"] };
    const TIMINGS = ["PRE_MATCH","BEFORE_POWER_ROLL","WIN","LOSE","HIT","UNOPPOSED","AFTER_DAMAGE_APPLY","RESOLVE_START","RESOLVE_STEP_END","RESOLVE_END","END_MATCH","END_ROUND","IMMEDIATE","BATTLE_START"];
    const TYPES = ["APPLY_STATE","APPLY_STATE_PER_N","MULTIPLY_STATE","APPLY_BUFF","GRANT_SKILL","REMOVE_BUFF","DAMAGE_BONUS","MODIFY_ROLL","USE_SKILL_AGAIN","CUSTOM_EFFECT","FORCE_UNOPPOSED","MODIFY_BASE_POWER","MODIFY_FINAL_POWER","DRAIN_HP","SUMMON_CHARACTER"];
    const TARGETS = ["","self","target","ALL_ENEMIES","ALL_ALLIES","ALL_OTHER_ALLIES","ALL","NEXT_ALLY"];
    const POWER_OPS = ["FIXED","FIXED_IF_EXISTS","PER_N_BONUS","MULTIPLY"];
    const COND_SOURCES = ["self","target","skill","target_skill","relation"];
    const COND_OPS = ["GTE","LTE","GT","LT","EQUALS","CONTAINS"];
    const HELP_ROWS = [["target_scope: same_team","同陣営単体を対象にする"],["tag: ally_target","同陣営単体タグ（互換）"],["tag: no_damage","非ダメージ扱い"],["timing: PRE_MATCH","マッチ前処理"],["timing: HIT/WIN/LOSE","命中時/勝利時/敗北時"],["type: APPLY_BUFF","buff_id / buff_name を付与"],["type: SUMMON_CHARACTER","summon_template_idを使って召喚"],["power_bonus: FIXED","固定加算（value）"],["power_bonus: FIXED_IF_EXISTS","paramが閾値以上で固定加算"],["power_bonus: PER_N_BONUS","Nごとに加算"],["power_bonus: MULTIPLY","param × value_per_param"],["buff_name: *_AtkN / *_DaInN","動的バフ命名で効果を自動解釈"]];
    const DYNAMIC_BUFF_PATTERNS = [
      { suffix: "_ActN",   meaning: "行動値 +N",                 effect: "stat_mods.行動値",                         example: "迅速_Act2",         regex: /^(.*)_Act(\d+)$/ },
      { suffix: "_AtkN",   meaning: "攻撃タグ時の最終威力 +N",   effect: "power_bonus(FIXED, apply_to=final)",     example: "猛攻_Atk5",         regex: /^(.*)_Atk(\d+)$/ },
      { suffix: "_AtkDownN", meaning: "攻撃タグ時の最終威力 -N", effect: "power_bonus(FIXED, apply_to=final)",     example: "弱体_AtkDown3",     regex: /^(.*)_AtkDown(\d+)$/ },
      { suffix: "_DefN",   meaning: "守備タグ時の最終威力 +N",   effect: "power_bonus(FIXED, apply_to=final)",     example: "守護_Def4",         regex: /^(.*)_Def(\d+)$/ },
      { suffix: "_DefDownN", meaning: "守備タグ時の最終威力 -N", effect: "power_bonus(FIXED, apply_to=final)",     example: "脆化_DefDown2",     regex: /^(.*)_DefDown(\d+)$/ },
      { suffix: "_PhysN",  meaning: "物理補正 +N",               effect: "stat_mods.物理補正",                       example: "剛力_Phys2",        regex: /^(.*)_Phys(\d+)$/ },
      { suffix: "_PhysDownN", meaning: "物理補正 -N",            effect: "stat_mods.物理補正",                       example: "鈍化_PhysDown2",    regex: /^(.*)_PhysDown(\d+)$/ },
      { suffix: "_MagN",   meaning: "魔法補正 +N",               effect: "stat_mods.魔法補正",                       example: "賢明_Mag2",         regex: /^(.*)_Mag(\d+)$/ },
      { suffix: "_MagDownN", meaning: "魔法補正 -N",             effect: "stat_mods.魔法補正",                       example: "沈黙_MagDown2",     regex: /^(.*)_MagDown(\d+)$/ },
      { suffix: "_CrackN", meaning: "亀裂付与量 +N（消費しない）", effect: "state_bonus(stat=亀裂, consume=false)",  example: "地裂_Crack1",       regex: /^(.*)_Crack(\d+)$/ },
      { suffix: "_CrackOnceN", meaning: "亀裂付与量 +N（1回消費）", effect: "state_bonus(stat=亀裂, consume=true)", example: "崩し_CrackOnce2",   regex: /^(.*)_CrackOnce(\d+)$/ },
      { suffix: "_DaInN",  meaning: "被ダメージ N% 増加",         effect: "incoming_damage_multiplier",               example: "脆弱_DaIn20",       regex: /^(.*)_DaIn(\d+)$/ },
      { suffix: "_DaCutN", meaning: "被ダメージ N% 減少",         effect: "incoming_damage_multiplier",               example: "防壁_DaCut15",      regex: /^(.*)_DaCut(\d+)$/ },
      { suffix: "_DaOutN", meaning: "与ダメージ N% 増加",         effect: "outgoing_damage_multiplier",               example: "激昂_DaOut20",      regex: /^(.*)_DaOut(\d+)$/ },
      { suffix: "_DaOutDownN", meaning: "与ダメージ N% 減少",     effect: "outgoing_damage_multiplier",               example: "衰弱_DaOutDown10",  regex: /^(.*)_DaOutDown(\d+)$/ },
      { suffix: "_BleedReactN", meaning: "被ダメ時に出血 +N",     effect: "on_damage_state(stat=出血)",               example: "呪血_BleedReact2",  regex: /^(.*)_BleedReact(\d+)$/ }
    ];
    const TAG_HINTS = ["攻撃","守備","広域","即時発動","マッチ不可","ラウンド終了","ally_target","no_damage","non_damage","同陣営指定"];
    let effectSeq = 0;

    function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
    function mkSelect(arr,v=""){const s=document.createElement("select");arr.forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x||"(未指定)";if(x===v)o.selected=true;s.appendChild(o)});return s;}
    function parseList(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
    function parseCost(v){const out=[];parseList(v).forEach(tok=>{const [t,n]=tok.split(":");const iv=Number(n);if(!t||Number.isNaN(iv))return;out.push({type:t.trim(),value:iv})});return out}
    function toNum(v){if(v==null||v==="")return undefined;const n=Number(v);return Number.isNaN(n)?undefined:n}
    function toBool(v){const s=String(v||"").trim().toLowerCase();if(!s)return undefined;if(["true","1","yes"].includes(s))return true;if(["false","0","no"].includes(s))return false;return undefined}

    function fillDatalist(id,items){const dl=document.getElementById(id);dl.innerHTML="";items.forEach(v=>{const o=document.createElement("option");o.value=v;dl.appendChild(o)})}
    function readCond(host){const source=host.querySelector(".condSource")?.value?.trim();const param=host.querySelector(".condParam")?.value?.trim();const operator=host.querySelector(".condOp")?.value?.trim();const rv=host.querySelector(".condVal")?.value?.trim();if(!source||!param||!operator||rv==="")return null;const n=Number(rv);return {source,param,operator,value:Number.isNaN(n)?rv:n}}
    function renderCond(host,seed={}){host.innerHTML="";const g=document.createElement("div");g.className="grid4";g.innerHTML=`<div><label>condition.source</label><select class="condSource">${COND_SOURCES.map(x=>`<option value="${x}" ${x===(seed.source||"target")?"selected":""}>${x}</option>`).join("")}</select></div><div><label>condition.param</label><input class="condParam" list="stateNameList" value="${esc(seed.param||"HP")}" /></div><div><label>condition.operator</label><select class="condOp">${COND_OPS.map(x=>`<option value="${x}" ${x===(seed.operator||"GTE")?"selected":""}>${x}</option>`).join("")}</select></div><div><label>condition.value</label><input class="condVal" value="${esc(seed.value??"")}" /></div>`;host.appendChild(g)}

    function addPowerBonusRow(seed={}){
      const row=document.createElement("div");row.className="row";
      row.innerHTML=`<div class="grid4"><div><label>operation</label><select class="pbOp">${POWER_OPS.map(x=>`<option value="${x}" ${x===(seed.operation||"FIXED")?"selected":""}>${x}</option>`).join("")}</select></div><div><label>source</label><select class="pbSource"><option value="self" ${(seed.source||"self")==="self"?"selected":""}>self</option><option value="target" ${(seed.source||"self")==="target"?"selected":""}>target</option></select></div><div><label>param</label><input class="pbParam" list="stateNameList" value="${esc(seed.param||"")}" /></div><div><label>apply_to</label><select class="pbApply"><option value="base" ${(seed.apply_to||"base")==="base"?"selected":""}>base</option><option value="dice" ${(seed.apply_to||"")==="dice"?"selected":""}>dice</option><option value="final" ${(seed.apply_to||"")==="final"?"selected":""}>final</option></select></div></div><div class="grid4" style="margin-top:8px;"><div data-show="FIXED,FIXED_IF_EXISTS,PER_N_BONUS"><label>value</label><input class="pbValue" type="number" step="any" value="${esc(seed.value??"")}"/></div><div data-show="PER_N_BONUS"><label>per_N</label><input class="pbPerN" type="number" value="${esc(seed.per_N??"")}"/></div><div data-show="FIXED_IF_EXISTS"><label>threshold</label><input class="pbThreshold" type="number" value="${esc(seed.threshold??1)}"/></div><div data-show="MULTIPLY"><label>value_per_param</label><input class="pbVpp" type="number" step="any" value="${esc(seed.value_per_param??"")}"/></div><div><label>max_bonus</label><input class="pbMax" type="number" value="${esc(seed.max_bonus??"")}"/></div><div><label>min_bonus</label><input class="pbMin" type="number" value="${esc(seed.min_bonus??"")}"/></div></div><div class="toolbar"><label><input type="checkbox" class="pbCondEnable" ${seed.condition?"checked":""}/> conditionを使う</label><button class="btn btn-danger" type="button">削除</button></div><div class="pbCond"></div><div><label>extra_json（任意）</label><input class="pbExtra mono" placeholder='{"custom":true}' /></div>`;
      const condHost=row.querySelector(".pbCond"); if(seed.condition)renderCond(condHost,seed.condition);
      const sync=()=>{const op=row.querySelector(".pbOp").value;row.querySelectorAll("[data-show]").forEach(el=>{const arr=el.dataset.show.split(",");el.style.display=arr.includes(op)?"block":"none"})};
      row.querySelector(".pbOp").addEventListener("change",()=>{sync();generate()});sync();
      row.querySelector(".pbCondEnable").addEventListener("change",e=>{condHost.innerHTML="";if(e.target.checked)renderCond(condHost,{});generate()});
      row.querySelector(".btn-danger").addEventListener("click",()=>{row.remove();generate()});
      row.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",generate));
      document.getElementById("pbRoot").appendChild(row);
    }

    function collectPowerBonus(){const out=[];document.querySelectorAll("#pbRoot .row").forEach(row=>{const r={operation:row.querySelector(".pbOp").value};const source=row.querySelector(".pbSource").value;const param=row.querySelector(".pbParam").value.trim();const apply=row.querySelector(".pbApply").value;if(source)r.source=source;if(param)r.param=param;if(apply&&apply!=="base")r.apply_to=apply;[["value",".pbValue"],["per_N",".pbPerN"],["threshold",".pbThreshold"],["value_per_param",".pbVpp"],["max_bonus",".pbMax"],["min_bonus",".pbMin"]].forEach(([k,sel])=>{const n=toNum(row.querySelector(sel).value);if(n!==undefined)r[k]=n});if(row.querySelector(".pbCondEnable").checked){const c=readCond(row.querySelector(".pbCond"));if(c)r.condition=c}const ex=row.querySelector(".pbExtra").value.trim();if(ex){try{const o=JSON.parse(ex);if(o&&typeof o==="object"&&!Array.isArray(o))Object.assign(r,o)}catch(_){}}out.push(r)});document.getElementById("powerBonusInput").value=JSON.stringify(out,null,2);return out}
    function addEffectRow(seed={}){
      const row=document.createElement("div");row.className="row";const id="e"+(++effectSeq);
      row.innerHTML=`<div class="grid3"><div><label>timing</label><select class="timingSel">${TIMINGS.map(x=>`<option value="${x}" ${x===(seed.timing||"HIT")?"selected":""}>${x}</option>`).join("")}</select></div><div><label>type</label><select class="typeSel">${TYPES.map(x=>`<option value="${x}" ${x===(seed.type||"APPLY_STATE")?"selected":""}>${x}</option>`).join("")}</select></div><div><label>target</label><select class="targetSel">${TARGETS.map(x=>`<option value="${x}" ${x===(seed.target||"target")?"selected":""}>${x||"(未指定)"}</option>`).join("")}</select></div></div><div class="grid4" style="margin-top:8px;"><div><label>state_name</label><input class="efState" list="stateNameList" value="${esc(seed.state_name||"")}"/></div><div><label>value</label><input class="efValue" type="number" step="any" value="${esc(seed.value??"")}"/></div><div><label>buff_id</label><input class="efBuffId" list="buffIdList" value="${esc(seed.buff_id||"")}"/></div><div><label>buff_name</label><input class="efBuffName" list="buffNameList" value="${esc(seed.buff_name||"")}"/></div><div><label>skill_id</label><input class="efSkillId" list="skillIdList" value="${esc(seed.skill_id||"")}"/></div><div><label>lasting</label><input class="efLasting" type="number" value="${esc(seed.lasting??"")}"/></div><div><label>delay</label><input class="efDelay" type="number" value="${esc(seed.delay??"")}"/></div><div><label>summon_template_id</label><input class="efSummonId" list="summonIdList" value="${esc(seed.summon_template_id||"")}"/></div></div><div class="toolbar"><label><input type="checkbox" class="efCondEnable" ${seed.condition?"checked":""}/> conditionを使う</label><button class="btn btn-danger" type="button">削除</button></div><div class="efCond"></div><div><label>extra_json（任意）</label><input class="efExtra mono" placeholder='{"rounds":3}' /></div>`;
      const cHost=row.querySelector(".efCond");if(seed.condition)renderCond(cHost,seed.condition);
      row.querySelector(".efCondEnable").addEventListener("change",e=>{cHost.innerHTML="";if(e.target.checked)renderCond(cHost,{});generate()});
      row.querySelector(".btn-danger").addEventListener("click",()=>{row.remove();generate()});
      row.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",generate));
      document.getElementById("effectsRoot").appendChild(row);
    }

    function collectEffects(){const out=[];document.querySelectorAll("#effectsRoot .row").forEach(row=>{const e={timing:row.querySelector(".timingSel").value,type:row.querySelector(".typeSel").value};const t=row.querySelector(".targetSel").value;if(t)e.target=t;[["state_name",".efState"],["buff_id",".efBuffId"],["buff_name",".efBuffName"],["skill_id",".efSkillId"],["summon_template_id",".efSummonId"]].forEach(([k,sel])=>{const v=row.querySelector(sel).value.trim();if(v)e[k]=v});[["value",".efValue"],["lasting",".efLasting"],["delay",".efDelay"]].forEach(([k,sel])=>{const n=toNum(row.querySelector(sel).value);if(n!==undefined)e[k]=n});if(row.querySelector(".efCondEnable").checked){const c=readCond(row.querySelector(".efCond"));if(c)e.condition=c}const ex=row.querySelector(".efExtra").value.trim();if(ex){try{const o=JSON.parse(ex);if(o&&typeof o==="object"&&!Array.isArray(o))Object.assign(e,o)}catch(_){}}out.push(e)});return out}

    function generate(){const data={};const tags=parseList(document.getElementById("tagsInput").value);if(tags.length)data.tags=tags;const ts=document.getElementById("targetScope").value;if(ts)data.target_scope=ts;const cost=parseCost(document.getElementById("costInput").value);if(cost.length)data.cost=cost;data.power_bonus=collectPowerBonus();data.effects=collectEffects();document.getElementById("jsonOut").textContent=JSON.stringify(data,null,2);return data}
    async function copyJson(){const txt=document.getElementById("jsonOut").textContent||"";if(!txt.trim())return;try{await navigator.clipboard.writeText(txt);document.getElementById("copyStatus").textContent="コピーしました"}catch(_){document.getElementById("copyStatus").textContent="コピー失敗"}setTimeout(()=>document.getElementById("copyStatus").textContent="",1500)}

    function renderHelp(){document.getElementById("helpTableBody").innerHTML=HELP_ROWS.map(([k,v])=>`<tr><td class="mono">${esc(k)}</td><td>${esc(v)}</td></tr>`).join("")}
    function renderState(){const arr=Array.isArray(REF.state_refs)?REF.state_refs:[];document.getElementById("stateRefRoot").innerHTML=arr.map(s=>`<span class="chip mono">${esc(s)}</span>`).join("")}
    function renderBuff(){const q=(document.getElementById("buffFilter").value||"").trim().toLowerCase();const rows=(REF.buff_refs||[]).filter(b=>`${b.id}\n${b.name}\n${b.description}\n${JSON.stringify(b.effect||{})}`.toLowerCase().includes(q));document.getElementById("buffTableBody").innerHTML=rows.map(b=>`<tr><td class="mono">${esc(b.id)}</td><td>${esc(b.name||"")}</td><td>${esc(b.description||"")}</td><td class="mono">${esc(JSON.stringify(b.effect||{}))}</td></tr>`).join("");document.getElementById("buffCount").textContent=`${rows.length} / ${(REF.buff_refs||[]).length} 件`}
    function renderSkill(){const q=(document.getElementById("skillFilter").value||"").trim().toLowerCase();const rows=(REF.skill_refs||[]).filter(s=>`${s.id}\n${s.name}\n${(s.tags||[]).join(",")}`.toLowerCase().includes(q));document.getElementById("skillTableBody").innerHTML=rows.map(s=>`<tr><td class="mono">${esc(s.id)}</td><td>${esc(s.name||"")}</td><td>${esc((s.tags||[]).join(", "))}</td></tr>`).join("");document.getElementById("skillCount").textContent=`${rows.length} / ${(REF.skill_refs||[]).length} 件`}
    function renderSummon(){const rows=REF.summon_refs||[];document.getElementById("summonTableBody").innerHTML=rows.map(s=>`<tr><td class="mono">${esc(s.id)}</td><td>${esc(s.name||"")}</td><td class="mono">${esc(s.summon_duration_mode||"")}</td><td class="mono">${esc(s.summon_duration??"")}</td></tr>`).join("");document.getElementById("summonCount").textContent=`${rows.length} 件`}
    function renderDynamicBuffPatterns(){document.getElementById("dynamicBuffTableBody").innerHTML=DYNAMIC_BUFF_PATTERNS.map(p=>`<tr><td class="mono">${esc(p.suffix)}</td><td>${esc(p.meaning)}</td><td class="mono">${esc(p.effect)}</td><td class="mono">${esc(p.example)}</td></tr>`).join("")}
    function checkDynamicBuffName(){const raw=(document.getElementById("dynamicBuffNameInput").value||"").trim();const out=document.getElementById("dynamicBuffMatch");if(!raw){out.textContent="";return}const hit=DYNAMIC_BUFF_PATTERNS.find(p=>p.regex.test(raw));if(!hit){out.textContent="一致パターンなし（静的buff_id指定か、名前を再確認してください）";return}const m=raw.match(hit.regex);const n=(m&&m[2])?m[2]:"";out.textContent=`一致: ${hit.suffix} / 解釈: ${hit.meaning.replace("N", n||"N")}`;}

    function initRef(){const states=Array.isArray(REF.state_refs)?REF.state_refs:[];const buffIds=(REF.buff_refs||[]).map(x=>x.id).filter(Boolean);const buffNames=(REF.buff_refs||[]).map(x=>x.name).filter(Boolean);const skillIds=(REF.skill_refs||[]).map(x=>x.id).filter(Boolean);const summonIds=(REF.summon_refs||[]).map(x=>x.id).filter(Boolean);const tags=new Set(TAG_HINTS);(REF.skill_refs||[]).forEach(s=>(s.tags||[]).forEach(t=>tags.add(String(t))));fillDatalist("stateNameList",states);fillDatalist("buffIdList",buffIds);fillDatalist("buffNameList",buffNames);fillDatalist("skillIdList",skillIds);fillDatalist("summonIdList",summonIds);fillDatalist("tagHintList",Array.from(tags).sort((a,b)=>a.localeCompare(b,"ja")));renderState();renderBuff();renderDynamicBuffPatterns();renderSkill();renderSummon()}

    function bind(){document.getElementById("addPbBtn").addEventListener("click",()=>{addPowerBonusRow();generate()});document.getElementById("clearPbBtn").addEventListener("click",()=>{document.getElementById("pbRoot").innerHTML="";addPowerBonusRow();generate()});document.getElementById("addEffectBtn").addEventListener("click",()=>{addEffectRow();generate()});document.getElementById("clearEffectBtn").addEventListener("click",()=>{document.getElementById("effectsRoot").innerHTML="";addEffectRow();generate()});document.getElementById("generateBtn").addEventListener("click",generate);document.getElementById("copyBtn").addEventListener("click",copyJson);document.getElementById("buffFilter").addEventListener("input",renderBuff);document.getElementById("skillFilter").addEventListener("input",renderSkill);document.getElementById("dynamicBuffNameInput").addEventListener("input",checkDynamicBuffName);["tagsInput","targetScope","costInput"].forEach(id=>{document.getElementById(id).addEventListener("input",generate);document.getElementById(id).addEventListener("change",generate)})}

    bind();renderHelp();initRef();addPowerBonusRow();addEffectRow();checkDynamicBuffName();generate();
  
